name: Process-PSModule

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  Process-PSModule:
    name: Process-PSModule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize-PSModule
        uses: PSModule/Initialize-PSModule@main
        with:
          Version: $null

      - name: Build-PSModule
        uses: PSModule/Build-PSModule@main

      # - name: Test-PSModule
      #   uses: PSModule/Test-PSModule@main

      # - name: Release-PSModule
      #   uses: PSModule/Release-PSModule@main
      #   with:
      #     APIKey: ${{ secrets.APIKEY }}
      #   env:
      #     GH_TOKEN: ${{ github.token }} # Used for GitHub CLI authentication
